hotel/urls.py
from django.contrib import admin
from django.urls import path
import krishna.views as views
urlpatterns = [
    path('', views.homepage,name="homepage"),
    path('home', views.homepage,name="homepage"),
    path('about', views.aboutpage,name="aboutpage"),
    path('contact', views.contactpage,name="contactpage"),
    path('user', views.user_log_sign_page,name="userloginpage"),
    path('user/login', views.user_log_sign_page,name="userloginpage"),
    path('user/bookings', views.user_bookings,name="dashboard"),
    path('user/book-room', views.book_room_page,name="bookroompage"),
    path('user/book-room/book', views.book_room,name="bookroom"),
    path('user/signup', views.user_sign_up,name="usersignup"),
    path('staff/', views.staff_log_sign_page,name="staffloginpage"),
    path('staff/login', views.staff_log_sign_page,name="staffloginpage"),
    path('staff/signup', views.staff_sign_up,name="staffsignup"),
    path('logout', views.logoutuser,name="logout"),
    path('staff/panel', views.panel,name="staffpanel"),
    path('staff/allbookings', views.all_bookings,name="allbookigs"),
    
    path('staff/panel/add-new-location', views.add_new_location,name="addnewlocation"),
    path('staff/panel/edit-room', views.edit_room),
    path('staff/panel/add-new-room', views.add_new_room,name="addroom"),
    path('staff/panel/edit-room/edit', views.edit_room),
    path('staff/panel/view-room', views.view_room),

    path('admin/', admin.site.urls),
    

]

krishna/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Hotels(models.Model):
    #h_id,h_name,owner ,location,rooms
    name = models.CharField(max_length=30,default="krishna")
    owner = models.CharField(max_length=20)
    location = models.CharField(max_length=50)
    state = models.CharField(max_length=50,default="maharashtra")
    country = models.CharField(max_length=50,default="india")
    def __str__(self):
        return self.name


class Rooms(models.Model):
    ROOM_STATUS = ( 
    ("1", "available"), 
    ("2", "not available"),    
    ) 

    ROOM_TYPE = ( 
    ("1", "premium"), 
    ("2", "deluxe"),
    ("3","basic"),    
    ) 

    #type,no_of_rooms,capacity,prices,Hotel
    room_type = models.CharField(max_length=50,choices = ROOM_TYPE)
    capacity = models.IntegerField()
    price = models.IntegerField()
    size = models.IntegerField()
    hotel = models.ForeignKey(Hotels, on_delete = models.CASCADE)
    status = models.CharField(choices =ROOM_STATUS,max_length = 15)
    roomnumber = models.IntegerField()
    def __str__(self):
        return self.hotel.name

class Reservation(models.Model):

    check_in = models.DateField(auto_now =False)
    check_out = models.DateField()
    room = models.ForeignKey(Rooms, on_delete = models.CASCADE)
    guest = models.ForeignKey(User, on_delete= models.CASCADE)
    
    booking_id = models.CharField(max_length=100,default="null")
    def __str__(self):
        return self.guest.username

templates/staff/addroom.html
{% extends 'basic.html' %}
{% block title %}Add Room
{% endblock title %}
{% block css %}
 <style>
        .progress {
            width: 150px;
            height: 150px;
            background: none;
            position: relative;
        }
        
        .progress::after {
            content: "";
            width: 100%;
            height: 100%;
            border-radius: 50%;
            border: 6px solid #eee;
            position: absolute;
            top: 0;
            left: 0;
        }
        
        .progress>span {
            width: 50%;
            height: 100%;
            overflow: hidden;
            position: absolute;
            top: 0;
            z-index: 1;
        }
        
        .progress .progress-left {
            left: 0;
        }
        
        .progress .progress-bar {
            width: 100%;
            height: 100%;
            background: none;
            border-width: 6px;
            border-style: solid;
            position: absolute;
            top: 0;
        }
        
        .progress .progress-left .progress-bar {
            left: 100%;
            border-top-right-radius: 80px;
            border-bottom-right-radius: 80px;
            border-left: 0;
            -webkit-transform-origin: center left;
            transform-origin: center left;
        }
        
        .progress .progress-right {
            right: 0;
        }
        
        .progress .progress-right .progress-bar {
            left: -100%;
            border-top-left-radius: 80px;
            border-bottom-left-radius: 80px;
            border-right: 0;
            -webkit-transform-origin: center right;
            transform-origin: center right;
        }
        
        .progress .progress-value {
            position: absolute;
            top: 0;
            left: 0;
        }
        
        
        body {
            min-height: 100vh;
        }
        
        .rounded-lg {
            border-radius: 1rem;
        }
        
        .text-gray {
            color: #aaa;
        }
        
        div.h4 {
            line-height: 1rem;
        }
    </style>
{% endblock css %}
{% block body %}
 <h1 class="text-center bg-warning my-0">Add Room</h1>
    <!--Staff section -->
    <div class="container">

        <div class="row">
            <div class="col-md-6 col-lg-6 col-xlg-6 col-sm-12 mx-auto">

                <form action="/staff/panel/add-room/add" method="POST">
                    {% csrf_token %}
                    
                    <div class="form-group">
                        <label for="email">Room Type:</label>
                        <select class="form-control" name="roomtype" id="roomtype">
                            
                            <option value="1">Premium</option>
                            <option value="2">Deluxe</option>
                            <option value="3">Basic</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Capacity:</label>
                        <input type="number" class="form-control " id="capacity" name="capacity">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Price:</label>
                        <input type="mumber" class="form-control " id="price" name="price">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Size:</label>
                        <input type="number" class="form-control " id="size" name="size">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Status:</label>
                        <select class="form-control" name="status" id="roomstatus">
                            
                            <option value="1">Available</option>
                            <option value="2">Not Available</option>
                            
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Location:</label>
                        
                        <select class="form-control" name="hotel" id="hotel">
                            {% for each_location,eachid in location%}
                            <option value={{eachid}}>{{each_location}}</option>
                            {% endfor %}
                            
                            
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Room</button>
                </form>
            </div>
        </div>
    </div>
{% endblock body %}
   

templates/staff/allbookings.html
{% extends 'basic.html' %}
{% block title %}All Bookings
{% endblock title %}
{% block body %}
<h3 class="text-center  text-success">All Bookings </h3>
<table class="table">
    <thead>
        <th>User</th>
        <th>Room</th>
        <th>Location</th>
        <th>Person</th>
        <th>Check in</th>
        <th>Check out</th>
        <th>Price</th>
    </thead>
    {% for each_booking in bookings %}
    <tr>
        <td>{{each_booking.guest.username}}</td>
        <td>{{each_booking.room.roomnumber}}</td>
        <td>{{each_booking.room.hotel.location}}</td>
        <td>{{each_booking.room.capacity}}</td>
        <td>{{each_booking.check_in}}</td>
        <td>{{each_booking.check_out}}</td>
        <td>{{each_booking.room.price}}</td>
    </tr>
    {% endfor %}


</table>
{% endblock body %}

templates/staff/editroom.html
{% extends 'basic.html' %}
{% block title %}Edit Room
{% endblock title %}
{% block css %}
<style>
        .progress {
            width: 150px;
            height: 150px;
            background: none;
            position: relative;
        }
        
        .progress::after {
            content: "";
            width: 100%;
            height: 100%;
            border-radius: 50%;
            border: 6px solid #eee;
            position: absolute;
            top: 0;
            left: 0;
        }
        
        .progress>span {
            width: 50%;
            height: 100%;
            overflow: hidden;
            position: absolute;
            top: 0;
            z-index: 1;
        }
        
        .progress .progress-left {
            left: 0;
        }
        
        .progress .progress-bar {
            width: 100%;
            height: 100%;
            background: none;
            border-width: 6px;
            border-style: solid;
            position: absolute;
            top: 0;
        }
        
        .progress .progress-left .progress-bar {
            left: 100%;
            border-top-right-radius: 80px;
            border-bottom-right-radius: 80px;
            border-left: 0;
            -webkit-transform-origin: center left;
            transform-origin: center left;
        }
        
        .progress .progress-right {
            right: 0;
        }
        
        .progress .progress-right .progress-bar {
            left: -100%;
            border-top-left-radius: 80px;
            border-bottom-left-radius: 80px;
            border-right: 0;
            -webkit-transform-origin: center right;
            transform-origin: center right;
        }
        
        .progress .progress-value {
            position: absolute;
            top: 0;
            left: 0;
        }
        /*
*
* ==========================================
* FOR DEMO PURPOSE
* ==========================================
*
*/
        
        body {
            min-height: 100vh;
        }
        
        .rounded-lg {
            border-radius: 1rem;
        }
        
        .text-gray {
            color: #aaa;
        }
        
        div.h4 {
            line-height: 1rem;
        }
    </style>
{% endblock css %}
{% block body %}
<h1 class="text-center bg-warning my-0">Edit Room</h1>
    <!--Staff section -->
    <div class="container">

        <div class="row">
            <div class="col-md-6 col-lg-6 col-xlg-6 col-sm-12 mx-auto">

                <form action="/staff/panel/edit-room/edit" method="POST">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="pwd">Room Number:</label>
                        <input type="number" class="form-control" id="roomnumber" name="roomnumber" value="{{room.roomnumber}}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="email">Room Type:</label>
                        <select class="form-control" name="roomtype" id="roomtype">
                            
                            
                            
                            <option  value=1>Premium</option>
                            <option  value=2>Deluxe</option>
                            <option  value=3>Basic</option>

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Capacity:</label>
                        <input type="number" class="form-control " id="capacity" name="capacity" value="{{room.capacity}}">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Price:</label>
                        <input type="mumber" class="form-control " id="price" name="price" value="{{room.price}}">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Size:</label>
                        <input type="number" class="form-control " id="size" name="size" value="{{room.size}}">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Status:</label>
                        <select class="form-control" name="status" id="status">
                            <option value="1">Available</option>
                            <option value="2">Not Available</option>
                            
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Location:</label>
                        <input type="text" class="form-control " id="hotel" name="hotel" value="{{room.hotel.location}}" disabled>
                    </div>
                    <button type="submit" class="btn btn-danger">Save</button>
                    <input type="hidden" name="roomid" value="{{room.id}}">
                    <input type="hidden" name="roomtypevalue" id="roomtypevalue" value="{{room.room_type}}">
                    <input type="hidden" name="roomstatus" id="roomstatus" value="{{room.status}}">
                    <input type="hidden" class="form-control " id="hotel" name="hotel" value="{{room.hotel.id}}">
                    <input type="hidden" class="form-control" id="roomnumber" name="roomnumber" value="{{room.roomnumber}}">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}
    {% block js %}
    <script>
    $(document).ready(function() {

        //for  room type
        var x = $("#roomtypevalue").val()
        $("#roomtype").val(Number(x)).attr("selected", "selected");

        //for room status
        var x = $("#roomstatus").val()
        $("#status").val(Number(x)).attr("selected", "selected");

    });
</script>
    {% endblock js %}
    






   

templates/staff/stafflogsign.html
{% extends 'basic.html' %}
{% block title %}staff
{% endblock title %}
{% block body %}
<!--Cards starts here-->
    <div class="container py-5">
        <!--login and signup tab starts here -->
        <section>
            <div class="card w-50 mx-auto">
                <div class="card-title bg-light ">
                    <div class="container mt-3 mx-auto">

                        <!-- Nav tabs -->
                        <ul class="nav nav-tabs justify-content-center w-100 " style="width:358px">

                            <li class="nav-item">
                                <a class="nav-link active " data-toggle="tab" href="#home" style="width:158px">Login</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#menu1" style="width:158px">Signup</a>
                            </li>

                    </div>
                </div>


                </ul>
                <div class="card-body">

                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div id="home" class="container tab-pane active">
                            <p class="text-center text-dark">Staff login form</p>
                            <div class="container">

                                <div class="row">
                                    <div class="col-md-12 col-lg-12 col-xlg-12">

                                        <form action="/staff/login" method="post">
                                            {%csrf_token%}
                                            <div class="form-group">
                                                <label for="email">username:</label>
                                                <input type="text" class="form-control " id="username" placeholder="username" name="username">
                                            </div>
                                            <div class="form-group">
                                                <label for="pwd">Password:</label>
                                                <input type="password" class="form-control " id="password" placeholder="password" name="password">
                                            </div>
                                            <div class="form-group form-check">
                                                <label class="form-check-label">
                                                        <input class="form-check-input " type="checkbox"
                                                            name="remember">
                                                        Remember me
                                                    </label>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Login</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="menu1" class="container tab-pane fade">
                            <p class="text-center text-dark">Staff Signup form</p>
                            <div class="container">

                                <div class="row">
                                    <div class="col-md-12 col-lg-12 col-xlg-12">

                                        <form action="/staff/signup" method="POST">
                                            {%csrf_token%}
                                            <div class="form-group">
                                                <label for="username">Username:</label>
                                                <input type="text" class="form-control " id="username" placeholder="Username" name="username">
                                            </div>
                                            <div class="form-group">
                                                <label for="password1">Password:</label>
                                                <input type="password" class="form-control " id="password1" placeholder="password" name="password1">
                                            </div>
                                            <div class="form-group">
                                                <label for="password2">Confirm Password:</label>
                                                <input type="password" class="form-control " id="password2" placeholder="Confirm Password" name="password2">
                                            </div>


                                            <button type="submit" class="btn btn-primary">Sign Up</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
        </section>
        <!--Login and logout tab ends here-->
    </div>
{% endblock body %}
    
   

templates/staff/viewroom.html
 {% extends 'basic.html' %} {% block title %}View Room {% endblock title %} {% block body %}
<h3 class="text-success"> Details</h3>
<hr>
<div class="container mx-0 ">
    <p><b>Number :-</b> {{room.roomnumber}}</p>
    <p><b>Type :-</b> {{room.get_room_type_display}}</p>
    <p><b>Capacity :-</b> {{room.capacity}} person</p>
    <p><b>Size :-</b> {{room.size}} ft</p>
    <p><b>Status :-</b> {{room.get_status_display| capfirst}} </p>
    <p><b>City :-</b> {{room.hotel.location| capfirst}} </p>
    <p><b>State :-</b> {{room.hotel.state| capfirst}} </p>
    <p><b>India :-</b> {{room.hotel.country| capfirst}} </p>
</div>


<hr> {% if reservations %}
<h3 class="text-success">Bookings :-</h3>
<table class="table">
    <thead>
        <th>Username</th>
        <th>Person</th>
        <th>check in</th>
        <th>check out</th>
    </thead>
    {% for each_detail in reservations %}
    <tr>
        <td>{{each_detail.guest.username}}</td>
        <td>{{each_detail.room.capacity}}</td>
        <td>{{each_detail.check_in}}</td>
        <td>{{each_detail.check_out}}</td>
    </tr>
    {% endfor %}
    <tr>
        <td><b>Total bookings = </b>{{reservations | length}}</td>
    </tr>

</table>
{% else %}
<p>No details found</p>
{% endif %} {% endblock body %}